# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Rapid Reservoir-River Temperature Assessment Model (R3TAM) 
author: James Gilbert, UC Santa Cruz
copyright: "2026"
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: r3tam_doc.tex


# limit subheading numbering
sections:
  numbered: 4

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/james-m-gilbert/r3tam  # Online location of your book
  path_to_book: docs/r3tam_documentation  # Optional path to your book, relative to the repository root
  branch: test-release  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
